receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'jmx-exporter'
          static_configs:
            - targets: ['localhost:9993']


exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
      Lightstep-Access-Token: "${LS_TOKEN}"




service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [debug,otlp]

